services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      - TZ=Asia/Jakarta
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - booking_net

volumes:
  db:

networks:
  booking_net:
    driver: bridge