scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 5s
    static_configs:
      - targets: ['otel-collector:8888']

  - job_name: 'booking-service'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8000']